stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:18-dind
  script:
    - export DOCKER_API_VERSION=1.39
    - docker login -u 'gitlab-ci-token' -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - master

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:18-dind
  before_script:
    - 'which ssh-agent || ( apk update && apk add openssh )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_SERVER" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp ./docker-compose.yml $SERVER_USER@$SERVER_IP:$DEPLOY_DIR
    - scp ./deploy.sh $SERVER_USER@$SERVER_IP:$DEPLOY_DIR

    - ssh $SERVER_USER@$SERVER_IP
      "cd $DEPLOY_DIR &&
      chmod +x ./deploy.sh &&
      ./deploy.sh $CI_JOB_TOKEN $CI_REGISTRY"

  only:
    - master