// SITE VERSION
export const SITE_VERSION = "0.0.1";
// APISTATE
export const SET_API = "apiState/SET_API";
// MODALSTATE
export const PUSH_MODAL = "modalState/PUSH_MODAL";
export const POP_MODAL = "modalState/POP_MODAL";
export const POP_ALL_MODAL = "modalState/POP_ALL_MODAL";
export const CLOSE_MODAL = "modal/CLOSE_MODAL";
export const CLOSE_ALL_MODAL = "modal/CLOSE_ALL_MODAL";
// USERSTATE
export const SET_USER_INFO = "userState/SET_USER_INFO";
export const USER_UPDATE = "userState/USER_UPDATE";
export const LOGOUT = "userState/LOGOUT";
// MODAL_COMPONENTS
export const MODAL_CREATE_NEW_ACCOUNT = "modal/MODAL_CREATE_NEW_ACCOUNT";
export const MODAL_INVITE = "modal/MODAL_INVITE";
export const MODAL_PROFILE = "modal/MODAL_PROFILE";
export const MODAL_IMAGE = "modal/MODAL_IMAGE";
export const MODAL_WATCHING = "modal/MODAL_WATCHING";
export const MODAL_MEMBERS = "modal/MODAL_MEMBERS";
export const MODAL_FOLLOWERS = "modal/MODAL_FOLLOWERS";
export const MODAL_USER_SETTINGS = "modal/MODAL_USER_SETTINGS";
export const MODAL_EDIT_USER_SETTINGS = "modal/MODAL_EDIT_USER_SETTINGS";
export const MODAL_CHANGE_PASSWORD = "modal/MODAL_CHANGE_PASSWORD";
export const MODAL_BLOCKED_USERS = "modal/MODAL_BLOCKED_USERS";
export const MODAL_DELETE_MESSAGE = "modal/MODAL_DELETE_MESSAGE";
// USERPAGE_STATE
export const USERPAGE_SET_USER_INFO = "USERPAGE/USERPAGE_SET_USER_INFO";
// USERSEARCH_STATE
export const USERSEARCH_SET_USERS_INFO = "USERSEARCH/USERSEARCH_SET_USERS_INFO";
export const USERSEARCH_SET_API = "USERSEARCH/SET_API";
