// SITE VERSION
export const SITE_VERSION = "0.0.2";
// APISTATE
export const SET_API = "apiState/SET_API";
// MODALSTATE
export const PUSH_MODAL = "modalState/PUSH_MODAL";
export const POP_MODAL = "modalState/POP_MODAL";
export const POP_ALL_MODAL = "modalState/POP_ALL_MODAL";
export const CLOSE_MODAL = "modal/CLOSE_MODAL";
export const CLOSE_ALL_MODAL = "modal/CLOSE_ALL_MODAL";
export const PUSH_MODAL_PROFILE_MODAL = "modal/PUSH_MODAL_PROFILE_MODAL";
export const PUSH_MODAL_DELETE_MESSAGE = "modal/PUSH_MODAL_DELETE_MESSAGE";
// USERSTATE
export const SET_USER_INFO = "userState/SET_USER_INFO";
export const USER_UPDATE = "userState/USER_UPDATE";
export const LOGOUT = "userState/LOGOUT";
// MODAL_COMPONENTS
export const MODAL_CREATE_NEW_ACCOUNT = "modal/MODAL_CREATE_NEW_ACCOUNT";
export const MODAL_INVITE = "modal/MODAL_INVITE";
export const MODAL_CREATE_ROOM = "modal/MODAL_CREATE_ROOM";
export const MODAL_PROFILE = "modal/MODAL_PROFILE";
export const MODAL_IMAGE = "modal/MODAL_IMAGE";
export const MODAL_WATCHING = "modal/MODAL_WATCHING";
export const MODAL_MEMBERS = "modal/MODAL_MEMBERS";
export const MODAL_FOLLOWERS = "modal/MODAL_FOLLOWERS";
export const MODAL_USER_SETTINGS = "modal/MODAL_USER_SETTINGS";
export const MODAL_EDIT_USER_SETTINGS = "modal/MODAL_EDIT_USER_SETTINGS";
export const MODAL_CHANGE_PASSWORD = "modal/MODAL_CHANGE_PASSWORD";
export const MODAL_BLOCKED_USERS = "modal/MODAL_BLOCKED_USERS";
export const MODAL_DELETE_MESSAGE = "modal/MODAL_DELETE_MESSAGE";
export const MODAL_ACCOUNT_SETTINGS = "modal/MODAL_ACCOUNT_SETTINGS";
export const MODAL_DELETE_ACCOUNT = "modal/MODAL_DELETE_ACCOUNT";
export const MODAL_ROOM_EXISTS = "modal/MODAL_ROOM_EXISTS";
// USERPAGE_STATE
export const USERPAGE_SET_USER_INFO = "USERPAGE/USERPAGE_SET_USER_INFO";
// USERSEARCH_STATE
export const USERSEARCH_SET_USERS_INFO = "USERSEARCH/USERSEARCH_SET_USERS_INFO";
export const USERSEARCH_SET_API = "USERSEARCH/SET_API";
// GENERAL_STATE
export const GENERAL_INIT = "GENERAL/GENERAL_INIT";
export const GENERAL_ADD_CHANNEL = "GENERAL/ADD_CHANNEL";
export const GENERAL_REMOVE_CHANNEL = "GENERAL/REMOVE_CHANNEL";
export const GENERAL_ADD_MEMBERS = "GENERAL/ADD_MEMBERS";
export const GENERAL_ADD_MESSAGES = "GENERAL/ADD_MESSAGES";
export const GENERAL_RESET = "GENERAL/GENERAL_RESET";
export const GENERAL_CREATE_ROOM = "GENERAL/GENERAL_CREATE_ROOM";
export const GENERAL_SET_ROOM_NAME = "GENERAL/GENERAL_SET_ROOM_NAME";
export const GENERAL_SET_DRAFT = "GENERAL/SET_DRAFT";
export const GENERAL_SET_SCROLLED = "GENERAL/SET_SCROLLED";
// INVITE_STATE
export const INVITE_CLEAR = "INVITE/INVITE_CLEAR";
export const INVITE_ADD_CHANNEL = "INVITE/INVITE_ADD_CHANNEL";
export const INVITE_ADD_SELECTED_FRIENDS = "INVITE/INVITE_ADD_SELECTED_FRIENDS";
export const INVITE_REMOVE_SELECTED_FRIENDS =
  "INVITE/INVITE_REMOVE_SELECTED_FRIENDS";
