// If you don't see an icon that you need, you can search it here https://fontawesome.com/
// Make sure to import the icon, and add it to the library.{}
// Usage Example 1: faTwitter -> icon={twitter}
// Usage Exmaple 2: faGlobleAmericas -> icon={globe-americas}

import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faTwitter as fabTwitter,
  faYoutube as fabYoutube,
  faDiscord as fabDiscord,
  faTwitch as fabTwitch,
  faInstagram as fabInstagram,
  faTiktok as fabTiktok,
  faFacebook as fabFacebook,
  faSpotify as fabSpotify
} from "@fortawesome/free-brands-svg-icons";
import {
  faGlobeAmericas,
  faPlus,
  faSearch,
  faPaperPlane,
  faShare,
  faTimes,
  faLock,
  faEllipsisV,
  faEllipsisH,
  faPlay,
  faPause,
  faGlobe,
  faMinus,
  faCog,
  faBell as fasBell,
  faInfoCircle,
  faBars,
  faSmile as fasSmile,
  faRedoAlt,
  faImage,
  faHeart,
  faVolumeUp,
  faVolumeMute,
  faCompress,
  faCheck,
  faArrowLeft,
  faArrowDown,
  faMoon,
  faHome,
  faFire,
  faUser,
  faUsers,
  faUserFriends,
  faUserCircle,
  faUserAltSlash,
  faUserEdit,
  faUserPlus,
  faUserCheck,
  faSignOutAlt,
  faAngleRight,
  faUnlockAlt,
  faExternalLinkAlt,
  faEdit,
  faLightbulb,
  faComment,
  faExpand
} from "@fortawesome/free-solid-svg-icons";
import {
  faSmile as farSmile,
  faImages as farImages,
  faBell as farBell,
  faHeart as farHeart,
  faComment as farComment,
  faMoon as farMoon
} from "@fortawesome/free-regular-svg-icons";

library.add(
  faGlobeAmericas,
  faGlobe,
  faPlus,
  faMinus,
  faSearch,
  faPaperPlane,
  faShare,
  faTimes,
  faLock,
  faEllipsisV,
  faEllipsisH,
  faPlay,
  faPause,
  faCog,
  fasBell,
  farBell,
  faInfoCircle,
  faBars,
  fasSmile,
  farSmile,
  farImages,
  faImage,
  faUser,
  faUsers,
  faUserFriends,
  faUserCircle,
  faUserAltSlash,
  faUserEdit,
  faUserPlus,
  faUserCheck,
  faRedoAlt,
  farHeart,
  farComment,
  faHeart,
  faVolumeUp,
  faVolumeMute,
  faCompress,
  faCheck,
  faArrowLeft,
  faArrowDown,
  faMoon,
  farMoon,
  faHome,
  faFire,
  faSignOutAlt,
  faAngleRight,
  faUnlockAlt,
  faExternalLinkAlt,
  faEdit,
  faLightbulb,
  faComment,
  // == Logos == //
  fabTwitter,
  fabYoutube,
  fabDiscord,
  fabTwitch,
  fabInstagram,
  fabTiktok,
  fabFacebook,
  fabSpotify,
  faExpand
);
